/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DispatchRouteImport } from './routes/dispatch'
import { Route as FloorRouteImport } from './routes/floor'
import { Route as LabelsRouteImport } from './routes/labels'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MaterialsRouteImport } from './routes/materials'
import { Route as OptimizerRouteImport } from './routes/optimizer'
import { Route as PackingRouteImport } from './routes/packing'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as TeamRouteImport } from './routes/team'
import { Route as UploadsRouteImport } from './routes/uploads'
import { Route as WhatsappRouteImport } from './routes/whatsapp'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminIdRouteImport } from './routes/admin.$id'
import { Route as AdminSecurityRouteImport } from './routes/admin.security'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsIdRouteImport } from './routes/projects.$id'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as ShopBomRouteImport } from './routes/shop.bom'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ProjectsIdIndexRouteImport } from './routes/projects.$id.index'
import { Route as ProjectsIdSubsSidRouteImport } from './routes/projects.$id.subs.$sid'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatchRoute = DispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const FloorRoute = FloorRouteImport.update({
  id: '/floor',
  path: '/floor',
  getParentRoute: () => rootRouteImport,
} as any)
const LabelsRoute = LabelsRouteImport.update({
  id: '/labels',
  path: '/labels',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialsRoute = MaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => rootRouteImport,
} as any)
const OptimizerRoute = OptimizerRouteImport.update({
  id: '/optimizer',
  path: '/optimizer',
  getParentRoute: () => rootRouteImport,
} as any)
const PackingRoute = PackingRouteImport.update({
  id: '/packing',
  path: '/packing',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadsRoute = UploadsRouteImport.update({
  id: '/uploads',
  path: '/uploads',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatsappRoute = WhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIdRoute = AdminIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSecurityRoute = AdminSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AdminRoute,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProjectsRoute,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopRoute,
} as any)
const ShopBomRoute = ShopBomRouteImport.update({
  id: '/bom',
  path: '/bom',
  getParentRoute: () => ShopRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdIndexRoute = ProjectsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsIdRoute,
} as any)
const ProjectsIdSubsSidRoute = ProjectsIdSubsSidRouteImport.update({
  id: '/subs/$sid',
  path: '/subs/$sid',
  getParentRoute: () => ProjectsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dispatch': typeof DispatchRoute
  '/floor': typeof FloorRoute
  '/labels': typeof LabelsRoute
  '/login': typeof LoginRoute
  '/materials': typeof MaterialsRoute
  '/optimizer': typeof OptimizerRoute
  '/packing': typeof PackingRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRouteWithChildren
  '/team': typeof TeamRoute
  '/uploads': typeof UploadsRoute
  '/whatsapp': typeof WhatsappRoute
  '/admin/$id': typeof AdminIdRoute
  '/admin/security': typeof AdminSecurityRoute
  '/projects/$id': typeof ProjectsIdRouteWithChildren
  '/shop/bom': typeof ShopBomRoute
  '/admin/': typeof AdminIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/projects/$id/': typeof ProjectsIdIndexRoute
  '/projects/$id/subs/$sid': typeof ProjectsIdSubsSidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dispatch': typeof DispatchRoute
  '/floor': typeof FloorRoute
  '/labels': typeof LabelsRoute
  '/login': typeof LoginRoute
  '/materials': typeof MaterialsRoute
  '/optimizer': typeof OptimizerRoute
  '/packing': typeof PackingRoute
  '/settings': typeof SettingsRoute
  '/team': typeof TeamRoute
  '/uploads': typeof UploadsRoute
  '/whatsapp': typeof WhatsappRoute
  '/admin/$id': typeof AdminIdRoute
  '/admin/security': typeof AdminSecurityRoute
  '/shop/bom': typeof ShopBomRoute
  '/admin': typeof AdminIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/shop': typeof ShopIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/projects/$id': typeof ProjectsIdIndexRoute
  '/projects/$id/subs/$sid': typeof ProjectsIdSubsSidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dispatch': typeof DispatchRoute
  '/floor': typeof FloorRoute
  '/labels': typeof LabelsRoute
  '/login': typeof LoginRoute
  '/materials': typeof MaterialsRoute
  '/optimizer': typeof OptimizerRoute
  '/packing': typeof PackingRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRouteWithChildren
  '/team': typeof TeamRoute
  '/uploads': typeof UploadsRoute
  '/whatsapp': typeof WhatsappRoute
  '/admin/$id': typeof AdminIdRoute
  '/admin/security': typeof AdminSecurityRoute
  '/projects/$id': typeof ProjectsIdRouteWithChildren
  '/shop/bom': typeof ShopBomRoute
  '/admin/': typeof AdminIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/projects/$id/': typeof ProjectsIdIndexRoute
  '/projects/$id/subs/$sid': typeof ProjectsIdSubsSidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dispatch'
    | '/floor'
    | '/labels'
    | '/login'
    | '/materials'
    | '/optimizer'
    | '/packing'
    | '/projects'
    | '/settings'
    | '/shop'
    | '/team'
    | '/uploads'
    | '/whatsapp'
    | '/admin/$id'
    | '/admin/security'
    | '/projects/$id'
    | '/shop/bom'
    | '/admin/'
    | '/projects/'
    | '/shop/'
    | '/api/auth/$'
    | '/projects/$id/'
    | '/projects/$id/subs/$sid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dispatch'
    | '/floor'
    | '/labels'
    | '/login'
    | '/materials'
    | '/optimizer'
    | '/packing'
    | '/settings'
    | '/team'
    | '/uploads'
    | '/whatsapp'
    | '/admin/$id'
    | '/admin/security'
    | '/shop/bom'
    | '/admin'
    | '/projects'
    | '/shop'
    | '/api/auth/$'
    | '/projects/$id'
    | '/projects/$id/subs/$sid'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dispatch'
    | '/floor'
    | '/labels'
    | '/login'
    | '/materials'
    | '/optimizer'
    | '/packing'
    | '/projects'
    | '/settings'
    | '/shop'
    | '/team'
    | '/uploads'
    | '/whatsapp'
    | '/admin/$id'
    | '/admin/security'
    | '/projects/$id'
    | '/shop/bom'
    | '/admin/'
    | '/projects/'
    | '/shop/'
    | '/api/auth/$'
    | '/projects/$id/'
    | '/projects/$id/subs/$sid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DispatchRoute: typeof DispatchRoute
  FloorRoute: typeof FloorRoute
  LabelsRoute: typeof LabelsRoute
  LoginRoute: typeof LoginRoute
  MaterialsRoute: typeof MaterialsRoute
  OptimizerRoute: typeof OptimizerRoute
  PackingRoute: typeof PackingRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  ShopRoute: typeof ShopRouteWithChildren
  TeamRoute: typeof TeamRoute
  UploadsRoute: typeof UploadsRoute
  WhatsappRoute: typeof WhatsappRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatch': {
      id: '/dispatch'
      path: '/dispatch'
      fullPath: '/dispatch'
      preLoaderRoute: typeof DispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/floor': {
      id: '/floor'
      path: '/floor'
      fullPath: '/floor'
      preLoaderRoute: typeof FloorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labels': {
      id: '/labels'
      path: '/labels'
      fullPath: '/labels'
      preLoaderRoute: typeof LabelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materials': {
      id: '/materials'
      path: '/materials'
      fullPath: '/materials'
      preLoaderRoute: typeof MaterialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/optimizer': {
      id: '/optimizer'
      path: '/optimizer'
      fullPath: '/optimizer'
      preLoaderRoute: typeof OptimizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packing': {
      id: '/packing'
      path: '/packing'
      fullPath: '/packing'
      preLoaderRoute: typeof PackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uploads': {
      id: '/uploads'
      path: '/uploads'
      fullPath: '/uploads'
      preLoaderRoute: typeof UploadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whatsapp': {
      id: '/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof WhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/$id': {
      id: '/admin/$id'
      path: '/$id'
      fullPath: '/admin/$id'
      preLoaderRoute: typeof AdminIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/security': {
      id: '/admin/security'
      path: '/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AdminSecurityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/shop/': {
      id: '/shop/'
      path: '/'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/bom': {
      id: '/shop/bom'
      path: '/bom'
      fullPath: '/shop/bom'
      preLoaderRoute: typeof ShopBomRouteImport
      parentRoute: typeof ShopRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id/': {
      id: '/projects/$id/'
      path: '/'
      fullPath: '/projects/$id/'
      preLoaderRoute: typeof ProjectsIdIndexRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/projects/$id/subs/$sid': {
      id: '/projects/$id/subs/$sid'
      path: '/subs/$sid'
      fullPath: '/projects/$id/subs/$sid'
      preLoaderRoute: typeof ProjectsIdSubsSidRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIdRoute: typeof AdminIdRoute
  AdminSecurityRoute: typeof AdminSecurityRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIdRoute: AdminIdRoute,
  AdminSecurityRoute: AdminSecurityRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ProjectsIdRouteChildren {
  ProjectsIdIndexRoute: typeof ProjectsIdIndexRoute
  ProjectsIdSubsSidRoute: typeof ProjectsIdSubsSidRoute
}

const ProjectsIdRouteChildren: ProjectsIdRouteChildren = {
  ProjectsIdIndexRoute: ProjectsIdIndexRoute,
  ProjectsIdSubsSidRoute: ProjectsIdSubsSidRoute,
}

const ProjectsIdRouteWithChildren = ProjectsIdRoute._addFileChildren(
  ProjectsIdRouteChildren,
)

interface ProjectsRouteChildren {
  ProjectsIdRoute: typeof ProjectsIdRouteWithChildren
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsIdRoute: ProjectsIdRouteWithChildren,
  ProjectsIndexRoute: ProjectsIndexRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

interface ShopRouteChildren {
  ShopBomRoute: typeof ShopBomRoute
  ShopIndexRoute: typeof ShopIndexRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopBomRoute: ShopBomRoute,
  ShopIndexRoute: ShopIndexRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DispatchRoute: DispatchRoute,
  FloorRoute: FloorRoute,
  LabelsRoute: LabelsRoute,
  LoginRoute: LoginRoute,
  MaterialsRoute: MaterialsRoute,
  OptimizerRoute: OptimizerRoute,
  PackingRoute: PackingRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  SettingsRoute: SettingsRoute,
  ShopRoute: ShopRouteWithChildren,
  TeamRoute: TeamRoute,
  UploadsRoute: UploadsRoute,
  WhatsappRoute: WhatsappRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
